/**
 * Created by Udea-Manager on 2018/1/22.
 */
export const UPDATE_DRAWMONEY = 'UPDATE_DRAWMONEY';
export const REMOVE_DRAWMONEY = 'REMOVE_DRAWMONEY';
export const UPDATE_WIDTHDRAW = 'UPDATE_WIDTHDRAW';
export const REMOVE_WIDTHDRAW = 'REMOVE_WIDTHDRAW';
